# Generated by Django 6.0.4 on 2026-05-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0003_asistencia_entrenador_rutina_socio_delete_persona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/', verbose_name='Avatar'),
        ),
    ]
