# Generated by Django 6.0.4 on 2026-05-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0004_socio_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='entrenadores/', verbose_name='Foto'),
        ),
    ]
