# Generated by Django 6.0.4 on 2026-04-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
